### ISSUE TITLE
Extra pixel of `#extra-pop-up` showing at top of the window in some devices (Chrome)

### ISSUE THREAD

**Issue by ZhengLinLei** [ZhengLinLei/spimhub#4]
![WhatsApp Image 2023-03-14 at 17 01 49](https://user-images.githubusercontent.com/77938581/225065392-7c7a11ea-e11c-4fe2-8674-4296915abd00.jpeg)

Chrome browser shows an extra pixel line from `#extra-pop-up` div. Please consider to add `top: -5px;` to prevent this ugly design. 🫡

**Comment by panquemao** [comment]
bro, stop calling me ugly

**Comment by ZhengLinLei** [comment]
@panquemao no, bro

**Comment by ZhengLinLei** [comment]
@panquemao issue fixed;

**Comment by ZhengLinLei** [comment]
Added `scss` code to `_index.scss`
```sass
   #extra-pop-up {
        // Exposed in some devices, hide it with -5px and then when it's active set it to 0
        top: -5px; // ----> Issue #4 (https://github.com/ZhengLinLei/spimhub/issues/4)
        &.active {
            top: .5px;
        }
    }
```
